services:
  # API NestJS (desenvolvimento)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: aee_digital_api:dev
    container_name: aee_digital_api
    ports:
      - '5001:5000'
      - '9229:9229'      # Debug remoto
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - aee_digital_backend

networks:
  aee_digital_backend:
    name: aee_digital_backend
    driver: bridge
