export const ANSWER_REPOSITORY = Symbol('ANSWER_REPOSITORY');
export const CENTRO_REPOSITORY = Symbol('CENTRO_REPOSITORY');
export const FORM_REPOSITORY = Symbol('FORM_REPOSITORY');
export const PASS_REPOSITORY = Symbol('PASS_REPOSITORY');
export const PERSON_REPOSITORY = Symbol('PERSON_REPOSITORY');
export const QUESTION_REPOSITORY = Symbol('QUESTION_REPOSITORY');
export const REGIONAL_REPOSITORY = Symbol('REGIONAL_REPOSITORY');
export const SUMMARY_REPOSITORY = Symbol('SUMMARY_REPOSITORY');
